backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "schedule"
    label: "SCHEDULE (スケジュール)"
    folder: "content/schedule"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "日時", name: "date", widget: "string", placeholder: "例：2026/04/01 19:00〜" }
      - { label: "場所", name: "location", widget: "string", required: false }
      - { label: "詳細", name: "body", widget: "markdown", required: false }

  - name: "pages"
    label: "INFORMATION (お知らせ)"
    folder: "content/pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "内容", name: "body", widget: "markdown" }
